#!/bin/bash

set -euxo pipefail

make docker
make -j32

git read-tree "$(git mktree </dev/null)"
git add -f \
    .gitbook.yaml \
    chapter*.md \
    cheatsheet.md \
    README.md \
    ROADMAP.md \
    SUMMARY.md \
    LICENSE
TREE="$(git write-tree)"
COMMIT="$(git commit-tree "$TREE" -p HEAD -m "publish" -S)"
if [ "$#" -eq 0 ] || [ ! "$1" = "--dry-run" ]; then
    git push --force-with-lease origin "$COMMIT:master"
    git reset --mixed
fi
